name: Integración Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🔧 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: 🧪 Ejecutar pruebas
        run: npm test
